logging:
    config: classpath:logback-spring.xml
mybatis:
    mapper-locations: classpath:/mappers/*Mapper.xml
pagehelper:
    helperDialect: mysql
    rowBoundsWithCount: true
server:
    max-http-header-size: 15360
    port: ${project.port}
    tomcat:
        uri-encoding: UTF-8
snowflake:
    datacenterId: 0
    machineId: 1
    startStmp: 1585625775330
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            filters: stat,wall,log4j2
            initial-size: 5
            maxActive: 20
            maxPoolPreparedStatementPerConnectionSize: 20
            maxWait: 60000
            min-idle: 5
            minEvictableIdleTimeMillis: 300000
            poolPreparedStatements: true
            stat-view-servlet:
                allow: 127.0.0.1,192.168.1.155,192.168.1.1,192.168.1.48
                login-password: ai187199876ai
                login-username: admin
                reset-enable: false
                url-pattern: /druid/*
            testOnBorrow: false
            testOnReturn: false
            testWhileIdle: true
            timeBetweenEvictionRunsMillis: 60000
            useGlobalDataSourceStat: true
            validationQuery: SELECT 'x'
            web-stat-filter:
                enabled: true
                exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
                url-pattern: /*
        password: ${project.dataBase}
        type: 'com.alibaba.druid.pool.DruidDataSource '
        url: jdbc:mysql://mysql:3306/${project.dataBase}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
        username: ${project.dataBase}
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    <#if  project.rabbitmq == true >
    rabbitmq:
        host: rabbitmq
        password: root
        port: 5672
        username: root
    </#if>
    redis:
        host: redis
        jedis:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: 30000ms
                min-idle: 1
        port: 6379
        timeout: 30000ms
    servlet:
        multipart:
            maxFileSize: -1
            maxRequestSize: -1
